name = Forge Web - Front Page
description = Layout for the front page of the Forge site
preview = preview.png
template = forge-web-front-page-layout

; Regions
regions[navigation]     = Navigation bar
regions[content]        = Content
regions[highlighted]    = Highlighted
regions[middle_content] = Middle content
regions[after_content]  = After content
regions[footer_left]    = Footer left
regions[footer_right]   = Footer right

; Stylesheets
stylesheets[all][] = css/layouts/forge_web_front_page/forge_web_front_page.layout.css
