name = Forge Web - Front Page
description = Layout for the front page of the Forge site
preview = preview.png
template = forge-web-front-page-layout

; Regions
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[content]        = Content
regions[after_content]  = After content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/forge_web_front_page/forge_web_front_page.layout.css
