<?php
/**
 * @file
 * Code for the Forge web offering feature.
 */

include_once 'forge_web_offering.features.inc';

/*
 * Implementation of hook_form_alter
 */
function forge_web_offering_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'offering_node_form') {
    $form['#validate'][] = 'forge_web_offering_custom_validation';
  }
}

/*
 * Custom validation
 */
function forge_web_offering_custom_validation($form, &$form_state) {
  if(!preg_match('/\d/', $form_state['values']['field_pricing_information']['en']['0']['value'])) {
    form_set_error('field_pricing_information', t('Pricing information must contains letters and at least one number.'));
  }
}
