<?php
/**
 * @file
 * Code for the Forge web offering feature.
 */

include_once 'forge_web_offering.features.inc';

/*
 * Implementation of hook_form_alter
 */
function forge_web_offering_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'offering_node_form' || $form_id == 'service_offering_node_form') {
    $form['#validate'][] = 'forge_web_offering_custom_validation';
  }
}

/*
 * Custom validation
 */
function forge_web_offering_custom_validation($form, &$form_state) {
  foreach($form_state['values']['field_pricing_information'] as $value) {
    if(!preg_match('/[A-Za-z]/', $value[0]['value']) || !preg_match('/[0-9]/', $value[0]['value'])) {
      form_set_error('field_pricing_information', t('Pricing information must contains letters and at least one number.'));
    }
  }
}

/*
 * implementation of hook_node_delete
 */
function forge_web_offering_node_delete($node) {
  _forge_web_offering_flush_cache($node);
}

/*
 * implementation of hook_node_insert
 */
function forge_web_offering_node_insert($node) {
  _forge_web_offering_flush_cache($node);
}

function _forge_web_offering_flush_cache($node) {
  if($node->type == 'offering' || $node->type == 'service_offering_julkict' || $node->type == 'service_offering') {
    cache_clear_all('offering_listing:', 'cache_views_data', TRUE);
  }
}
