name = Forge Web
description = Layout for the public site of Forge
preview = preview.png
template = forge-web-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer_left]    = Footer left
regions[footer_right]   = Footer right

; Stylesheets
stylesheets[all][] = css/layouts/forge_web/forge_web.layout.css
