name = Forge Web
description = Layout for the public site of Forge
preview = preview.png
template = forge-web-layout

; Regions
regions[navigation]     = Navigation bar
regions[help]           = Help
regions[highlighted]    = Highlighted
regions[hero]           = Hero
regions[before_content] = Before content
regions[content]        = Content
regions[under_content]  = Under content
regions[after_content]  = After content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer_left]    = Footer left
regions[footer_right]   = Footer right

; Stylesheets
stylesheets[all][] = css/layouts/forge_web/forge_web.layout.css
